#!/usr/bin/env bash
# Installs Nginx and add a file
sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
